# Import Libraries

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[1:8:2]

array([1, 3, 5, 7])

### Broadcasting

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2D array

In [18]:
arr_2D = np.array([[5, 10, 15], [20, 25, 30], [100, 200, 300]])
arr_2D

array([[  5,  10,  15],
       [ 20,  25,  30],
       [100, 200, 300]])

In [20]:
arr_2D.shape  # row x col

(3, 3)

In [21]:
arr_2D[0]

array([ 5, 10, 15])

In [22]:
arr_2D[2]

array([100, 200, 300])

In [24]:
arr_2D[1,1]

25

In [25]:
arr_2D[0,2]

15

#### Slicing

In [26]:
arr_2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])