# Import the Libraries

In [ ]:
import numpy as np

# Create np arrays

In [13]:
# Create normal python list
pyList = [1, 2, 3, 4]

In [10]:
type(pyList)

list

In [14]:
# Convert it to np array
np_array = np.array(pyList)

In [12]:
type(np_array)

numpy.ndarray

In [15]:
matrix = [[2, 4, 6], [1, 2, 3], [3, 6, 9]]
matrix

[[2, 4, 6], [1, 2, 3], [3, 6, 9]]

In [17]:
# 2D np array
np_matrix = np.array(matrix)
np_matrix

array([[2, 4, 6],
       [1, 2, 3],
       [3, 6, 9]])

#### Buid in numpy methods

In [23]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### NumPy Random

In [50]:
np.random.rand(5)

array([0.80418289, 0.55887309, 0.76156272, 0.52619182, 0.68745037])

In [52]:
np.random.rand(3,4)

array([[0.34687722, 0.37272674, 0.76755892, 0.34654785],
       [0.01322599, 0.57655488, 0.94725287, 0.0858172 ],
       [0.56102953, 0.89415318, 0.91740113, 0.98391479]])

In [55]:
np.random.randn(3)

array([-0.82211669, -0.61741828, -0.33011791])

In [56]:
np.random.randn(3,4)

array([[ 0.61154957, -1.38412646, -0.24607973, -0.57043995],
       [-1.13965062,  0.65895207,  0.06084124,  0.97753258],
       [-1.12493849, -0.90757584,  0.27706869,  2.45106507]])

In [73]:
np.random.randint(5)

2

In [71]:
np.random.randint(0,10,5)

array([2, 4, 7, 3, 5])

In [77]:
np.random.randint(0,10,(3,4))

array([[7, 8, 1, 6],
       [8, 4, 1, 2],
       [6, 6, 7, 7]])

### NumPy Methods that can performe

In [79]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [91]:
arr.shape

(25,)

In [92]:
arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr2.shape

(5, 5)

In [95]:
arr3 = arr.reshape(1,25)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [96]:
arr3.shape

(1, 25)

In [97]:
arr4 = arr.reshape(25,1)
arr4

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [98]:
arr4.shape

(25, 1)

In [85]:
ranArr = np.random.randint(0, 255, 25)
ranArr

array([120, 143, 164,  47, 137,  10, 223,  37,  65, 163,  82, 253, 181,
       137,  42, 138, 167, 251,  39, 209,  36,  46,   4,  53,  45])

In [90]:
ranArr.shape

(25,)

In [86]:
ranArr.max()

253

In [87]:
ranArr.min()

4

In [88]:
ranArr.argmax()

11

In [89]:
ranArr.argmin()

22